FROM openjdk:21-jdk-slim

WORKDIR /opt/camellia

RUN mkdir -p /opt/camellia

COPY  /home/runner/work/camellia/camellia/camellia-redis-proxy/camellia-redis-proxy-bootstrap/target/camellia-redis-proxy-bootstrap-.*.jar  /opt/camellia/camellia-redis-proxy-bootstrap.jar

RUN jar xvf camellia-redis-proxy-bootstrap.jar

RUN rm -rf camellia-redis-proxy-bootstrap.jar

RUN echo "java -XX:+UseG1GC -Xms128m -Xmx4096m -server org.springframework.boot.loader.JarLauncher" > start.sh

RUN chmod +x start.sh

RUN apt update  -y  && apt install net-tools vim  bc jq  redis-tools curl procps -y 

ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini-amd64 /usr/local/bin/tini

RUN chmod +x /usr/local/bin/tini

ENTRYPOINT ["/usr/local/bin/tini", "--"]

CMD ["sleep","infinity"]
          
          
