{
 "title": "hot-key",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "query_result(up{job = \"test3\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "uptime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "uptime{instance=~\"$node\", job=\"test3\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "start_time",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "start_time{instance=~\"$node\", job=\"test3\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "cpu_num",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cpu{instance=~\"$node\", type=\"cpu_num\", job=\"test3\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "work_thread_num",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "thread{instance=~\"$node\", job=\"test3\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "info",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "info{job=\"test3\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "cpu",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpu{instance=~\"$node\", type=\"usage\", job=\"test3\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(memory_info{instance=~\"$node\", job=\"test3\"}) without (instance)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "gc",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 3 },
     "targets": [
      {
       "expr": "sum(gc{instance=~\"$node\",job=\"test3\"}) without (instance)",
       "legendFormat": "{{name}}/{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "client_connect",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "client_connect{job=\"test3\", instance=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "qps",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "qps{job=\"test3\", instance=~\"$node\"}",
       "legendFormat": "qps"
      }
     ]
    },
    {
     "title": "qps_detail",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(qps_detail{job=\"test3\", instance=~\"$node\"}) without (instance,type)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "queue_pending",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "queue{job=\"test3\", instance=~\"$node\", type=\"pending\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "queue_discard",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "queue{job=\"test3\", instance=~\"$node\", type=\"discard\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "hot_key",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "hot_key",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "hot_key{job=\"test3\", instance=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}