{
 "title": "id_gen",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "query_result(up{job = \"test4\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "uptime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "uptime{instance=~\"$node\", job=\"test4\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "start_time",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "start_time{instance=~\"$node\", job=\"test4\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "cpu_num",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cpu{instance=~\"$node\", type=\"cpu_num\", job=\"test4\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "info",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "info{job=\"test4\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "cpu",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 3 },
     "targets": [
      {
       "expr": "cpu{instance=~\"$node\", type=\"usage\", job=\"test4\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum(memory_info{instance=~\"$node\", job=\"test4\"}) without (instance)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "gc",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 3 },
     "targets": [
      {
       "expr": "sum(gc{instance=~\"$node\",job=\"test4\"}) without (instance)",
       "legendFormat": "{{name}}/{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "request_count",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(request{job=\"test4\", instance=~\"$node\", type=\"count\", code=\"200\"}) without(instance)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "request_count_fail",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 2 },
     "targets": [
      {
       "expr": "sum(request{job=\"test4\", instance=~\"$node\", type=\"count\", code!=\"200\"}) without(instance)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "request_rt（avg）",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 2 },
     "targets": [
      {
       "expr": "avg(request{job=\"test4\", instance=~\"$node\", type=\"spendAvg\", code=\"200\"}) without(instance,code)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "request_rt",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "request{job=\"test4\", instance=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}