{
 "title": "delay-queue",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "query_result(up{job = \"test2\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "uptime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "uptime{instance=~\"$node\", job=\"test2\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "start_time",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "start_time{instance=~\"$node\", job=\"test2\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "cpu_num",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cpu{instance=~\"$node\", type=\"cpu_num\", job=\"test2\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "info",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "info{job=\"test2\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "cpu",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 3 },
     "targets": [
      {
       "expr": "cpu{instance=~\"$node\", type=\"usage\", job=\"test2\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum(memory_info{instance=~\"$node\", job=\"test2\"}) without (instance)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "gc",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 3 },
     "targets": [
      {
       "expr": "sum(gc{instance=~\"$node\",job=\"test2\"}) without (instance)",
       "legendFormat": "{{name}}/{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "event",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "send_msg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum without(instance) (request{job=\"test2\", instance=~\"$node\", type=~\"sendMsg\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "ack_msg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 2 },
     "targets": [
      {
       "expr": "sum without(instance) (request{job=\"test2\", instance=~\"$node\", type=~\"ackMsg\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "delete_msg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 2 },
     "targets": [
      {
       "expr": "sum without(instance) (request{job=\"test2\", instance=~\"$node\", type=~\"deleteMsg\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "get_msg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 15, "y": 2 },
     "targets": [
      {
       "expr": "sum without(instance) (request{job=\"test2\", instance=~\"$node\", type=~\"getMsg\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "pull_msg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum without(instance) (request{job=\"test2\", instance=~\"$node\", type=~\"pullMsg\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "trigger_msg_end_life",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 10 },
     "targets": [
      {
       "expr": "sum without(instance) (request{job=\"test2\", instance=~\"$node\", type=~\"triggerMsgEndLife\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "trigger_msg_ready",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 10 },
     "targets": [
      {
       "expr": "sum without(instance) (request{job=\"test2\", instance=~\"$node\", type=\"triggerMsgReady\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "trigger_msg_timeout",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 15, "y": 10 },
     "targets": [
      {
       "expr": "sum without(instance) (request{job=\"test2\", instance=~\"$node\", type=\"triggerMsgTimeout\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "time_gap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "pull_msg_time_gap（avg）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "pull_msg_time_gap{job=\"test2\", instance=~\"$node\", type=\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "pull_msg_time_gap",
     "type": "table",
     "gridPos": { "h": 10, "w": 13, "x": 7, "y": 3 },
     "targets": [
      {
       "expr": "pull_msg_time_gap{job=\"test2\", instance=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ready_queue_time_gap（avg）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "ready_queue_time_gap{job=\"test2\", instance=~\"$node\", type=\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "ready_queue_time_gap",
     "type": "table",
     "gridPos": { "h": 10, "w": 13, "x": 7, "y": 13 },
     "targets": [
      {
       "expr": "ready_queue_time_gap{job=\"test2\", instance=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "topic_info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "ready_queue_size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "topic_info{job=\"test2\", instance=~\"$node\", type=\"readyQueueSize\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "ready_queue_size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "targets": [
      {
       "expr": "topic_info{job=\"test2\", instance=~\"$node\", type=\"readyQueueSize\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "waiting_queue_size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "targets": [
      {
       "expr": "topic_info{job=\"test2\", instance=~\"$node\", type=\"waitingQueueSize\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "0_1min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topic_info{job=\"test2\", instance=~\"$node\", type=\"size_0_1min\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "1min_10min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topic_info{job=\"test2\", instance=~\"$node\", type=\"size_1min_10min\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "10min_30min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topic_info{job=\"test2\", instance=~\"$node\", type=\"size_10min_30min\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "30min_1hour",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topic_info{job=\"test2\", instance=~\"$node\", type=\"size_30min_1hour\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "1hour_6hour",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topic_info{job=\"test2\", instance=~\"$node\", type=\"size_1hour_6hour\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "6hour_1day",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topic_info{job=\"test2\", instance=~\"$node\", type=\"size_0_1min\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "1day_7day",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topic_info{job=\"test2\", instance=~\"$node\", type=\"size_1day_7day\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "7day_30day",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topic_info{job=\"test2\", instance=~\"$node\", type=\"size_7day_30day\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "30day_infinite",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topic_info{job=\"test2\", instance=~\"$node\", type=\"size_30day_infinite\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  }
 ]
}