{
 "title": "Camellia Redis Proxy",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": {
     "query": "label_values(redis_proxy_connect_count, instance)"
    }
   },
   {
    "name": "bid",
    "query": {
     "query": "label_values(redis_proxy_bid_bgroup, bid)"
    }
   },
   {
    "name": "bgroup",
    "query": {
     "query": "label_values(redis_proxy_bid_bgroup{bid=~\"$bid\"}, bgroup)"
    }
   },
   {
    "name": "quantile",
    "query": {
     "query": "label_values(redis_proxy_spend_stats, quantile)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_proxy_connect_count{instance=~\"$Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(redis_proxy_fail{instance=~\"$Instance\"}[1m])) by (reason)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Commands per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(redis_proxy_total_command{instance=~\"$Instance\"}[1m])) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(redis_proxy_spend_stats{quantile=\"$quantile\"}[1m])) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "RPS per Tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(redis_proxy_bid_bgroup{bid=~\"$bid\", bgroup=~\"$bgroup\"}[1m])) by (bid, bgroup)",
     "legendFormat": "{{bid}}|{{bgroup}}"
    }
   ]
  },
  {
   "title": "CPS per Tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(redis_proxy_detail{bid=~\"$bid\", bgroup=~\"$bgroup\"}[1m])) by (bid, bgroup, command)",
     "legendFormat": "{{bid}}|{{bgroup}}: {{command}}"
    }
   ]
  },
  {
   "title": "Route Configuration",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "redis_proxy_route_conf{bid=~\"$bid\", bgroup=~\"$bgroup\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(redis_proxy_slow_command_stats{bid=~\"$bid\", bgroup=~\"$bgroup\"}[1m])) by (bid, bgroup, command)",
     "legendFormat": "{{bid}}|{{bgroup}}: {{command}}"
    }
   ]
  },
  {
   "title": "Redis connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "redis_proxy_redis_connect_stats{}",
     "legendFormat": "{{redis_addr}}"
    }
   ]
  },
  {
   "title": "Latency per Upstream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(redis_proxy_upstream_redis_spend_stats{quantile=\"$quantile\"}[1m])) by (redis_addr)",
     "legendFormat": "{{redis_addr}}"
    }
   ]
  }
 ]
}