# Default values for Redis.
# -- Override the base name for resources
nameOverride: ""
# -- Override the full name for resources (includes the release name)
fullnameOverride: ""
camellia:
  image:
    name: "docker-registry-local.ecouser.net/ops/camellia:1.4.0-jdk-21-0.0.1"
    pullPolicy: "IfNotPresent"
  replicas: 2
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      cpu: 5000m
      memory: 4096Mi
  # -- Annotations for the camellia pod
  podAnnotations: {}
  # -- Node selector rules for the camellia pod
  nodeSelector: {}
  # -- Tolerations for the camellia pod
  tolerations: []
  # -- Affinity rules for the camellia pod
  affinity: {} 
redis: 
  image:
    name: "docker-registry.ecouser.net/library/redis:5.0"
    # -- Pull policy for the Redis image
    pullPolicy: "IfNotPresent"
  config:
    # -- Name of secret from which to get the Redis password. If set,
    # `config.secretKey` must also be set.
    # @default -- Do not require authentication
    secretName: ""
    # -- Key inside secret from which to get the Redis password. If set,
    # `config.secretName` must also be set.
    # @default -- Do not require authentication
    secretKey: ""
  persistence:
    # -- Whether to persist Redis storage and thus tokens. Setting this to false
    # will use `emptyDir` and reset all tokens on every restart.
    enabled: false
    # -- Amount of persistent storage to request
    size: "1Gi"
    # -- Class of storage to request
    storageClass: ""
    # -- Access mode of storage to request
    accessMode: "ReadWriteOnce"
    k8up:
      # -- Whether to enable k8up backup of the redis PVC
      enabled: false
    # -- Use an existing PVC, not dynamic provisioning. If this is set, the
    # size, storageClass, accessMode and k8up settings are ignored.
    volumeClaimName: ""
  # -- Resource limits and requests for the Redis pod
  resources: {}
  # -- Annotations for the Redis pod
  podAnnotations: {}
  # -- Node selector rules for the Redis pod
  nodeSelector: {}
  # -- Tolerations for the Redis pod
  tolerations: []
  # -- Affinity rules for the Redis pod
  affinity: {}
