apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-replicas" (include "common.names.fullname" .) }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '16379' 
    prometheus.io/services:   'false'
    prometheus.io/path: '/metrics'
spec:
  ports:
    - port: 16379
      protocol: TCP
      name: exporter
    - port: 6380
      protocol: TCP
      name: tcp
  selector:
    {{- include "camellia.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
