{
 "title": "New dashboard1",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "query_result(up{job = \"test1\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "uptime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "uptime{instance=~\"$node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "start_time",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "start_time{instance=~\"$node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "cpu_num",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cpu{instance=~\"$node\", type=\"cpu_num\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "work_thread_num",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "thread{instance=~\"$node\", type=\"work_thread\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "info",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "proxy_info{instance=~\"$node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "cpu",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpu{instance=~\"$node\", type=\"usage\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "sum(memory_info{instance=~\"$node\"}) without (instance)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "GC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
     "targets": [
      {
       "expr": "sum(gc{instance=~\"$node\"}) without (instance)",
       "legendFormat": "{{name}}/{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "proxy frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "client_connect",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "client_connect{instance=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "QPS（avg/max）",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(qps{instance=~\"$node\"}) without (instance)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "command_QPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(command_qps{instance=~\"$node\"}) without (instance)",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "command_avg_rt",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(command_spend_stats{instance=~\"$node\", type=\"avg\"}) without (instance)",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "command_rt（ms）",
     "type": "table",
     "gridPos": { "h": 9, "w": 16, "x": 8, "y": 11 },
     "targets": [
      {
       "expr": "command_spend_stats{instance=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "proxy frontend（tenant）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "tenant_client_connect",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(client_connect_detail{instance=~\"$node\"}) without (instance)",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "tenant_QPS",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(tenant_qps{instance=~\"$node\"}) without (instance)",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "tenant_command_QPS",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "tenant_command_qps{instance=~\"$node\"}",
       "legendFormat": "{{instance}}#{{command}}"
      }
     ]
    },
    {
     "title": "tenant_command_avg_rt",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "tenant_command_spend_stats{instance=~\"$node\", type=\"avg\"}",
       "legendFormat": "{{tenant}}#{{instance}}#{{command}}"
      }
     ]
    },
    {
     "title": "tenant_command_rt（ms）",
     "type": "table",
     "gridPos": { "h": 11, "w": 16, "x": 8, "y": 14 },
     "targets": [
      {
       "expr": "tenant_command_spend_stats{instance=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "proxy upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "proxy_route_conf",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "proxy_route_conf{instance=~\"$node\"}",
       "legendFormat": "{{instance}}#{{tenant}}"
      }
     ]
    },
    {
     "title": "upstream_redis_connect",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
     "targets": [
      {
       "expr": "sum(upstream_redis_connect{instance=~\"$node\"}) without (instance)",
       "legendFormat": "connect"
      }
     ]
    },
    {
     "title": "upstream_redis_connect_detail",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
     "targets": [
      {
       "expr": "sum(upstream_redis_connect_detail{instance=~\"$node\"}) without (instance)",
       "legendFormat": "{{upstream}}"
      }
     ]
    },
    {
     "title": "upstream_redis_qps",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(upstream_redis_qps{instance=~\"$node\"}) without (instance)",
       "legendFormat": "{{upstream}}"
      }
     ]
    },
    {
     "title": "upstream_redis_rt（ms）",
     "type": "table",
     "gridPos": { "h": 11, "w": 16, "x": 8, "y": 13 },
     "targets": [
      {
       "expr": "upstream_redis_spend_stats{instance=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "proxy fail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "client_fail",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "client_fail{instance=~\"$node\"}",
       "legendFormat": "{{instance}}#{{reason}}"
      }
     ]
    },
    {
     "title": "upstream_fail",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 9, "y": 5 },
     "targets": [
      {
       "expr": "upstream_fail{instance=~\"$node\"}",
       "legendFormat": "intstance={{instance}}, upstream={{upstream}}, command={{command}}, msg={{msg}}"
      }
     ]
    }
   ]
  },
  {
   "title": "proxy slow command",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "slow_command",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "slow_command{instance=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "proxy bigkey",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "string_big_key",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 13, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "string_big_key{instance=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "collection_big_key",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 13, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "collection_big_key{instance=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "proxy hotkey",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "hot_key（qps）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "hot_key{instance=~\"$node\", type=\"qps\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "hot_key（ops）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 9, "y": 8 },
     "targets": [
      {
       "expr": "hot_key{instance=~\"$node\", type=\"count\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "proxy hotkey cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "hot_key_cache_hit",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 10, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "hot_key_cache_hit{instance=~\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}