FROM 48n6e/openjdk:21-jdk-slim

WORKDIR /opt/camellia

RUN mkdir -p /opt/camellia

COPY  camellia-redis-proxy-bootstrap.jar  /opt/camellia/camellia-redis-proxy-bootstrap.jar

RUN jar xvf camellia-redis-proxy-bootstrap.jar

RUN rm -rf camellia-redis-proxy-bootstrap.jar

RUN echo "java -XX:+UseG1GC -XX:+UseContainerSupport -Dio.netty.tryReflectionSetAccessible=true --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.math=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.security=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.base/java.time=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/jdk.internal.access=ALL-UNNAMED --add-opens java.base/jdk.internal.misc=ALL-UNNAMED --add-opens java.base/sun.net.util=ALL-UNNAMED -Xms128m -Xmx4096m -server org.springframework.boot.loader.JarLauncher" > start.sh

RUN chmod +x start.sh

RUN apt update  -y  && apt install net-tools vim  bc jq  redis-tools curl procps -y 

ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini-amd64 /usr/local/bin/tini

RUN chmod +x /usr/local/bin/tini

ENTRYPOINT ["/usr/local/bin/tini", "--"]

CMD ["bash","start.sh"]
