{
 "title": "camellia-redis-proxy-概览",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(proxy_info,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "代理基本信息",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(uptime{cluster=~\"$cluster\"}) by (cluster,instance)"
    },
    {
     "expr": "max(start_time{cluster=~\"$cluster\"}) by (cluster,instance)"
    },
    {
     "expr": "sum(thread{cluster=~\"$cluster\"}) by (cluster,instance)"
    },
    {
     "expr": "sum(client_connect{cluster=~\"$cluster\"}) by (cluster,instance)"
    },
    {
     "expr": "max(proxy_info{cluster=~\"$cluster\"}) by (cluster,instance)"
    }
   ]
  },
  {
   "title": "客户端连接数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(client_connect{cluster=~\"$cluster\"}) by (cluster)"
    }
   ]
  },
  {
   "title": "客户端执行错误",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sum(client_fail{cluster=~\"$cluster\"}) by (reason)) "
    }
   ]
  },
  {
   "title": "客户端QPS（command）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(command_qps{cluster=~\"$cluster\"}) by (command)"
    }
   ]
  },
  {
   "title": "客户端QPS（max）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(qps{cluster=~\"$cluster\",type=~\"max.*\"}) by (type)"
    }
   ]
  },
  {
   "title": "客户端QPS（avg）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(qps{cluster=~\"$cluster\",type!~\"max.*\"}) by (cluster,type)"
    }
   ]
  },
  {
   "title": "客户端命令延时(avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(command_spend_stats{ cluster=~\"$cluster\", type=\"avg\"}) by (command)"
    }
   ]
  },
  {
   "title": "客户端命令延时(P90)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(command_spend_stats{ cluster=~\"$cluster\", type=\"p90\"}) by (command,type)"
    }
   ]
  },
  {
   "title": "客户端命令延时(P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(command_spend_stats{ cluster=~\"$cluster\", type=\"p99\"}) by (command,type)"
    }
   ]
  },
  {
   "title": "upstream连接数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(upstream_redis_connect{cluster=~\"$cluster\"}) by (cluster)"
    }
   ]
  },
  {
   "title": "QPS(upstream)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(upstream_redis_qps{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "upstream_fail",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "upstream_fail{cluster=~\"$cluster\"}",
     "legendFormat": "intstance={{instance}}, upstream={{upstream}}, command={{command}}, msg={{msg}}"
    }
   ]
  },
  {
   "title": "upstream延时(avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max (upstream_redis_spend_stats{cluster=~\"$cluster\",type=\"avg\"}) by (type)"
    }
   ]
  },
  {
   "title": "upstream延时(P90)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max (upstream_redis_spend_stats{cluster=~\"$cluster\",type=\"p90\"}) by (type)"
    }
   ]
  },
  {
   "title": "upstream延时(P99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max (upstream_redis_spend_stats{cluster=~\"$cluster\",type=\"p99\"}) by (type)"
    }
   ]
  },
  {
   "title": "string_big_key",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "string_big_key{cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "slow_command",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "slow_command{cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "hot_key（ops）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hot_key{cluster=~\"$cluster\", type=\"count\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "hot_key（qps）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hot_key{cluster=~\"$cluster\", type=\"qps\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}